### ISSUE TITLE
"return cardNumber"

### ISSUE THREAD

**Issue by shmulim** [learn-co-students/js-basics-online-shopping-lab-v-000#8]
The readme states:

> Define a function addCreditCard which accepts a credit card number as parameter. The function should store the number passed in as a parameter to the cardNumber variable. The function should print out to the console "Your credit card number has been saved." and return cardNumber.

The tests pass only when the function doesn't return _anything_.

**Comment by JVThomas** [comment]
No it works if you return the card. 

Your code has you initializing a local var cardNumber that is used in your method. Since all assignments are applied to that local variable and not the global cardNumber you initialized at the top of the file, the test will fail when it compares the return value to the global variable via spec. Error would end up being "Expected <value>(return) to be undefined(global var). 

Just remove the var in front of cardNumber and the assignment will be applied to the global variable. From there output to console.log and then return cardNumber.

**Comment by gj** [comment]
Outdated issue — should be all fixed up now. Thanks!
